import Nav from './components/Nav'
import './globals.css'
import { Oxygen } from 'next/font/google'

const oxygen = Oxygen({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={oxygen.className}>
        <main className='max-w-[1440] mx-auto relative z-10  min-h-screen flex flex-col items-center '>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  )
}
